name: "Testing Post Release"
on:
  workflow_dispatch:
jobs:
  testing_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'release - no nested folder'
        uses: jdaugherty/grails-github-actions/post-release@pr-troubleshooting